### ISSUE TITLE
Turned off "Require branches to be up to date before merging"

### ISSUE THREAD

**Issue by jeffkaufman** [jeffkaufman/nomic#18]
I initially set up "protected branches" in a very conservative way, with Require branches to be up to date before merging" enabled.  Unfortunately this means that if we have:

* Person A opens a PR, gets all approvals
* Person B opens a PR, gets all approvals
* Person A merges their PR

Then person B needs to sync and get all new approvals.

Because the check always runs against master at the time it runs, I think we can turn it off, and allow person B's to go in without re-running.  This is slightly less safe, but much less annoying.  The main way this could be a problem is if someone figured out how to make a safe-looking change that after merging with master was unsafe, but I think that's really hard.

<img width="745" alt="screen shot 2019-01-05 at 9 30 50 am" src="https://user-images.githubusercontent.com/262566/50725523-b8202d00-10cc-11e9-9d8e-86995df39508.png">

**Comment by pavellishin** [comment]
👍

**Comment by jeffkaufman** [comment]
Turned this back on, since #217 shows we do need it.

**Comment by jeffkaufman** [comment]
<img width="856" alt="screen shot 2019-02-07 at 1 27 18 pm" src="https://user-images.githubusercontent.com/262566/52433907-25fcb180-2adc-11e9-9db1-6c648475745d.png">

**Comment by jeffkaufman** [comment]
<img width="861" alt="screen shot 2019-02-07 at 1 29 29 pm" src="https://user-images.githubusercontent.com/262566/52434044-6fe59780-2adc-11e9-8946-5666b655cf01.png">

**Comment by jeffkaufman** [comment]
After clicking "update branch" the checks were invalidated and re-run:

<img width="859" alt="screen shot 2019-02-07 at 1 31 15 pm" src="https://user-images.githubusercontent.com/262566/52434136-ad4a2500-2adc-11e9-8e81-614990ca24ce.png">

So this looks like it fixes it!
