### ISSUE TITLE
Handling of unresponsive players

### ISSUE THREAD

**Issue by jeffkaufman** [jeffkaufman/nomic#19]
Right now, here's a way the game could end in a draw:

* Person A requests to be added to players.txt
* Everyone playing approves their PR, we merge it
* Person A loses interest in the game and stops approving things
* Because we currently require 100% approval, the game can't proceed.

This makes me nervous about accepting a lot of join requests, since it only takes one person to block the whole game.

I think we need something that allows PRs to go in with lower levels of approval.  What about:

* For each day since a PR has been merged, the required threshold for approval decreases by one player?

**Comment by pavellishin** [comment]
What about counting up the total approvals/denials after X days, where X is somewhere around a week?

e.g., if you open a PR on Monday, and on Wednesday it has 3 approvals out of 10 players, it gets merged?

I'm also trying to haphazardly follow this game on a Saturday morning after a toddler kicked me awake, so I don't think I fully understand how the rules regarding unblocking merges work.

**Comment by pavellishin** [comment]
Another idea, that would have to be complementary to this one: Every pull request also removes any players who have been "idle" for too long, making them ineligible to win the game at all.

(I wonder if it's plausible/possible in this particular implementation to have a scheduled task...)

**Comment by jeffkaufman** [comment]
@pavellishin a different way to implement that would be to update validate.sh so if a PR is a straightforward removal of a player, and that player hasn't been active in a week, then that PR doesn't require any approvals

**Comment by tnelling** [comment]
How do you define "active"?

**Comment by jeffkaufman** [comment]
@tnelling one way to define active would be, someone is "active" if they made actions within the last N days.  This could be reviewing a PR (approve, reject, comment), opening an issue, or commenting on an issue?  Though I don't know if this can be implemented efficiently against github's api.

**Comment by jeffkaufman** [comment]
#23 is merged now; let's reopen if this becomes a problem
