### ISSUE TITLE
Again, again!

### ISSUE THREAD

**Issue by pavellishin** [jeffkaufman/nomic#218]
But this time, I'm thinking maybe we make it harder to win by points alone...

**Comment by tnelling** [comment]
We could have a winners file that's out of bounds, and is only modifiable when the game is in inactive mode.

**Comment by tnelling** [comment]
Ideally, Travis itself would be capable of setting the game to inactive mode in response to someone winning, but I don't know if we can set that up.

**Comment by tnelling** [comment]
We could also keep track of who played in each game. I'm pretty sure I'm the worst player right now (0/3), but only because @pavellishin technically was never a player in game 3.

**Comment by jeffkaufman** [comment]
The game is reset and ready to play again (e5229a56a942126dc35c463d0f94f348b3d5389a, 701c4f5), but I didn't remove players this time since it was so short.  If people are done they can remove themselves.

**Comment by jeffkaufman** [comment]
@tnelling resetting the game is almost always going to have to happen manually, because we need to fix whatever bug led to the person winning last time and clean up any messes they may have made.

**Comment by jeffkaufman** [comment]
@tnelling I don't see any need for a winners file to be in the game itself, any more than there needs to be a list in my Power Grid set of who won each game.

**Comment by jeffkaufman** [comment]
In this case the only fix I made was setting "require branches to be up to date" (#18)

**Comment by csvoss** [comment]
I'm currently quasi-traveling, so I should probably drop out this time.
