### ISSUE TITLE
Dashboard shows need for re-review when it's not necessary

### ISSUE THREAD

**Issue by tnelling** [jeffkaufman/nomic#227]
Result of merging #222 

Example: I've approved #225, and the build output reflects this, but the dashboard says I need to re-review it.

**Comment by jeffkaufman** [comment]
This is going to be annoying to fix.

I need to get "has the diff changed" available to the JS.

**Comment by jeffkaufman** [comment]
I think this is fixed now; let me know if you run into any problems.
