### ISSUE TITLE
ban sockpuppets?

### ISSUE THREAD

**Issue by jeffkaufman** [jeffkaufman/nomic#245]
In the discussion on #226 we talked about whether we need to ban sockpuppets, and then in testing #242 I created a new user, `nomic-user` and had them create #244.  If you click on #244 as anything other than `nomic-user` you'll get a 404 because that account has been "flagged", which seems like shadowbanning.  The message suggests I contact support, but then I wasn't sure if this was actually legit.  Looking in the terms of service https://help.github.com/articles/github-terms-of-service/ I see "you may not have more than one free Account" so I think it's not.

It sounds like we should ban sockpuppets, since we don't want the game to be encouraging anyone to violate the GitHub terms of service.  Any objections?

**Comment by tnelling** [comment]
None whatsoever. I mentioned one account per player in #226 and I think it's a good idea.

**Comment by pavellishin** [comment]
👍

**Comment by jeffkaufman** [comment]
Ok, sockpuppets are banned.
