### ISSUE TITLE
Relax rules for quitting

### ISSUE THREAD

**Issue by jmitchell** [jeffkaufman/nomic#25]
In PR #11 and similar ones @jeffkaufman says:

> I'm ok with this going in, as long as you promise to submit a PR to remove yourself from players.txt if you get bored and want to stop playing.

This is a reasonable request, but may not be sufficient to keep the game running. Game modifications, including removing players, freeze as long as >1 player is unresponsive (related: #19). If the game gets stuck for too long people will lose interest.

**Comment by jeffkaufman** [comment]
What do you think of #23 for this?

**Comment by pavellishin** [comment]
> A related matter raised in #17 is how to streamline joining.

I proposed a solution in #16, I don't know how well it would work though.

**Comment by jeffkaufman** [comment]
#23 is merged now.  Let's reopen if this becomes a problem.
