### ISSUE TITLE
Any contributor can close a Github PR

### ISSUE THREAD

**Issue by pavellishin** [jeffkaufman/nomic#30]
I just realized that as a contributor, I have the power to close pull requests.

Is there a way to set Github up to prevent us from closing pull requests, and only have the original player, TravisCI, or @jeffkaufman (as owner of the game at this point) have that power?

**Comment by tnelling** [comment]
I'm so tempted to close this issue just to demonstrate that it applies here as well. But I suppose it isn't as big a deal with issues as it is with PRs.

**Comment by jeffkaufman** [comment]
Anyone can reopen them too, right?

**Comment by pavellishin** [comment]
> Anyone can reopen them too, right?

Sure, once they notice it's been closed. To be honest, I'm more worried about people accidentally closing PRs than I am about malicious actors, but I can definitely see someone closing down a PR as the clock winds towards the "majority approved, therefore Travis approved" deadline.

I think. You know what, I'm still not entirely sure how I go about winning this game :P

**Comment by tnelling** [comment]
I think it's worth fixing, but if left unfixed it's not game-breaking.

**Comment by jeffkaufman** [comment]
I still don't see why it matters.  Open vs closed is just a bit flip any of us can make, and doesn't do anything.

**Comment by tnelling** [comment]
I disagree that it doesn't do anything. The fact that it's reversible doesn't mean it's a no-op (ugh, so many negatives, and this is after wordsmithing to reduce >.<).

That said, I don't think this needs to be addressed with any urgency unless we see related degenerate behavior.

**Comment by pavellishin** [comment]
I'll close this for now and re-open if it becomes a problem.
