### ISSUE TITLE
PR 32 is still failing to validate

### ISSUE THREAD

**Issue by TheJhyde** [jeffkaufman/nomic#41]
#32 has 7 votes in favor and no rejections, so it should be valid to merge. But it's still failing the travis checks. When I run validate.py locally, it's rejected because sligocki, tnelling, and vesche all rejected it. But they all subsequently approved it, so I'm not sure what's up.

**Comment by jeffkaufman** [comment]
It looks like what's happening is:

1. @sligocki rejected it
2. changes pushed
3. @sligocki approved it
4. changes pushed

We allow approvals only for the current commit (so the approval at 3 is ignored) but persist rejections from any past step, so validate.py still thinks @sligocki is rejecting.

I'll make a PR to fix this.
