### ISSUE TITLE
Read-only access to the repo's settings page

### ISSUE THREAD

**Issue by tnelling** [jeffkaufman/nomic#42]
I'm trying to set up my own fork of the repo to also be able to run travis in the same way this repo does, but I can't see (e.g.) the branch protection rules.

@jeffkaufman

**Comment by jeffkaufman** [comment]
I don't know if there's a way to let people have read-only access, but here are the branch protection rules:

<img width="749" alt="screen shot 2019-01-08 at 9 41 17 pm" src="https://user-images.githubusercontent.com/262566/50873465-3e1ecb00-138e-11e9-94cd-8005e679da89.png">

**Comment by tnelling** [comment]
That's not all I was looking for, but it may actually be all I could get from what I asked.

The Travis CI docs suggest all I should need to do is include a travis.yml file (which of course I have, since I forked this repo) in order to trigger builds, but I don't have the option to trigger builds in GitHub (though I can on Travis itself). And as a consequence, I have no status checks to target for the rule settings.

**Comment by jeffkaufman** [comment]
@tnelling I think you probably haven't configured Travis fully for your fork. Did you follow their getting started guide?

**Comment by jeffkaufman** [comment]
I think Travis needs to be added as a GitHub integration

**Comment by tnelling** [comment]
Yeah, I gave it access to the repository, and it shows up in the repository's settings as an integration. The getting started guide only talks about the travis.yml file (and adding the integration), unless you're referring to something other than https://docs.travis-ci.com/user/tutorial/

**Comment by jmitchell** [comment]
@tnelling, does the "Re-build" link not show for you at https://github.com/tnelling/nomic/runs/47738356? It doesn't for me, but I assume it would for you and any collaborators you've added to your fork.

**Comment by tnelling** [comment]
Now I'm even more confused. It does show up there for me, but I still have no option to run a build against my PR, and I don't know how you even got that link, or how to navigate to it from within my project.

**Comment by tnelling** [comment]
Well... whatever the issue is, it's something to do with my "Add a file" test PR, as I just created a PR off the same branch as #44 and I can run a build against it.
