### ISSUE TITLE
Is the win condition "break Travis on master" or "break Travis on master and announce a winner"?

### ISSUE THREAD

**Issue by pavellishin** [jeffkaufman/nomic#51]
Is the win condition "break Travis on master" or "break Travis on master and announce a winner"?

The latter seems much harder to do; I don't know how long we want this game to go on, but maybe an easier win condition would be preferable.

**Comment by jeffkaufman** [comment]
It's currently the latter.  If players unanimously want to switch to the former we could, but I suspect there are too many ways to do that.

**Comment by sligocki** [comment]
My 2c: I would much prefer a game in which we try to build rules we all understand clearly, but are combined in unexpected ways. Rather than a game in which I have to painstakingly read API definitions to figure out if they could raise any exception in any circumstances.

**Comment by sligocki** [comment]
That said, it would also be fun if someone added any win condition :)

**Comment by jeffkaufman** [comment]
@sligocki I have some ideas, but I think I shouldn't send out more PRs straight now...
