### ISSUE TITLE
New game?

### ISSUE THREAD

**Issue by jeffkaufman** [jeffkaufman/nomic#85]
I'm trying to figure out whether we should restart the game.  There are two questions: (a) who would want to play and (b) what state should we put the repo back into?  Let's figure out (a) and then once we have players we can sort out the repo.

Who wants to play again? @tnelling @csvoss @vesche @pavellishin @shaunagm @sligocki

**Comment by tnelling** [comment]
I want to play, but I'd like to know if this Diplomacy thing is actually happening.

**Comment by pavellishin** [comment]
I also want to play; I think we should implement the changes in #77 that I didn't get around to really reading, and then crank everyone's points back to zero.

Maybe also pare the rules down to the bare minimum; maybe #77 already suggests that?

**Comment by shaunagm** [comment]
What does it mean to restart the game?

**Comment by sligocki** [comment]
I'm out. Thanks for the game all.

**Comment by jeffkaufman** [comment]
I decided to do (b) by fiat, merging #76 and implementing #77.  The state is now wiped, and I'm the only player.

Anyone who wants to play can join by sending a PR to give themself some points.

**Comment by jeffkaufman** [comment]
@sligocki bye!  it was fun playing with you!

**Comment by jeffkaufman** [comment]
> Can someone recap what happened with the old game? I had a busy last few days and haven't been paying attention.

Summary is https://www.jefftk.com/p/nomic-report-iii-conclusion
