### ISSUE TITLE
Update the list of repo collaborators

### ISSUE THREAD

**Issue by tnelling** [jeffkaufman/nomic#90]
Currently, I believe @csvoss is not listed as a repo collaborator, and many of last game's players are (most relevantly @sligocki). I'm fine with not purging the list until it's clear people aren't rejoining, but we should at least update those two.

**Comment by tnelling** [comment]
We might actually be able to automate this: https://developer.github.com/v3/repos/collaborators/

Would/should such a change be in-bounds? I'd tend to think not. For one thing, it should only ever run on `master`, because we only want to change the list of collaborators when a player is actually added or removed, by virtue of a merge to `master`. For another, this is more of a utility/convenience thing, and currently collaborator status is not intended to determine or reflect game status. And the update probably wouldn't even take place inside `validate.py`.

We could add another script (e.g. `update-collaborators.py`) that runs after `validate.py` only on `master`. The downside to this, of course, is that it's downstream of whatever anyone might be doing with `validate.py`, but since the list of collaborators isn't something that can really be used to gain an advantage I don't think anyone would have cause to mess with it.

**Comment by tnelling** [comment]
Created #92 to give an idea of what this might involve.

**Comment by jeffkaufman** [comment]
list is up to date for now (though it includes @vesche and @shaunagm who may or may not rejoin)

**Comment by vesche** [comment]
I'm gonna sit out for now @jeffkaufman Thanks for the game!
